### ISSUE TITLE
The expanded size of the tensor (100000) must match the existing size (20733) at non-singleton dimension 0

### ISSUE THREAD

**Issue by Nickgonzales76017** [Alec-Wright/AI-GuitarAmpModelling#7]
**process at time of error**
$ python dist_model_recnet.py -l "RNN3-acoustic1-pre"
no saved model found, creating new network
cuda device not available/not selected
unimplemented audio data type conversion...
unimplemented audio data type conversion...
unimplemented audio data type conversion...
unimplemented audio data type conversion...
unimplemented audio data type conversion...
unimplemented audio data type conversion...
Epoch:  1
current learning rate: 0.005
Epoch:  2

**Error**
Traceback (most recent call last):
  File "dist_model_recnet.py", line 190, in <module>
    val_output, val_loss = network.process_data(dataset.subsets['val'].data['input'][0],
  File "C:\Users\nickg\Automated-GuitarAmpModelling\CoreAudioML\networks.py", line 115, in process_data
    output[l * chunk:(l + 1) * chunk] = self(input_data[l * chunk:(l + 1) * chunk])
RuntimeError: The expanded size of the tensor (100000) must match the existing size (20733) at non-singleton dimension 0.  Target sizes: [100000, 1, 1].  Tensor sizes: [20733, 1, 1]

**System**
python 3.8.6
pytorch==0.1.2
torchvision==0.1.6
pytorch_lightning==1.1.0
numpy==1.19.4
scipy==1.5.4
matplotlib==3.3.3

**Comment by bboylalu** [comment]
Sorry for answering so late, but I just encountered this issue. This error is cause by the length of the -input and -target audio files. It has to be identical down to the sample.
